version: '3.8'

services:
  web: 
    build: .
    env_file:
      - .env
    ports: 
      - 3000:3000
    volumes:
      - .:/usr/src/app
    command: air src/main.go -b 0.0.0.0
  bd: 
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_Password=${DB_USER}
      - POSTGRES_DB=${DB_NAME}

    ports: 
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
    
volumes:
 postgres-db: